package narrative

// Default is the message catalog. en + ko are maintained together
// (FR-35c, CLAUDE.md hard rule): every key added here MUST land in both
// locales in the same change — TestCatalogParity enforces it.
//
// Template variety (NFR-8) grows alongside the narrative systems; feed
// keys start with one voice each and gain variants when the variety
// criteria are set.
var Default = Catalogs{
	LocaleEN: {
		// Live feed
		"feed.drift.grew":       "{player} ({club}) is improving — {attr} {from} → {to}.",
		"feed.drift.declined":   "{player} ({club}) is fading — {attr} {from} → {to}.",
		"feed.window.opened":    "The {window} transfer window is open.",
		"feed.window.closed":    "The {window} transfer window has closed.",
		"feed.season.ended":     "Season {season} has come to an end.",
		"feed.match.kickoff":    "Kick-off: {home} v {away} ({competition}, round {round}).",
		"feed.match.result":     "Full time: {home} {home_goals}–{away_goals} {away} ({competition}).",
		"feed.cup.result":       "Cup: {home} {home_goals}–{away_goals} {away} — {winner} advance.",
		"feed.matchday.preview": "Matchday preview: {count} fixtures scheduled for {month}/{day} at {kickoff_time}.",
		"feed.matchday.results": "Matchday round-up: {count} results filed from the {kickoff_time} window.",
		"feed.cup.champion":     "{club} lift the cup — champions of season {season}!",

		// Live match commentary (docs/02 §4). Params are ints/strings
		// only — never a float (it would reach the world hash via LiveMatch).
		"comment.kickoff":           "We're under way at {home} v {away}.",
		"comment.goal.1":            "GOAL! {player} finds the net for {club} — it's {home_goals}–{away_goals}.",
		"comment.goal.2":            "{player} strikes! {club} celebrate — {home_goals}–{away_goals}.",
		"comment.goal.3":            "It's in! {player} scores for {club}. {home_goals}–{away_goals}.",
		"comment.goal.4":            "{player} lashes it home for {club}! The stand erupts — {home_goals}–{away_goals}.",
		"comment.goal.5":            "A ruthless finish from {player}; {club} have their breakthrough. {home_goals}–{away_goals}.",
		"comment.goal.6":            "{player} times the run, takes one look, and buries it for {club}. The scoreboard jumps to {home_goals}–{away_goals}.",
		"comment.goal.7":            "The move opens up in a flash — {player} arrives and smashes {club} into celebration. {home_goals}–{away_goals}.",
		"comment.goal.8":            "No hesitation from {player}: first touch, finish, noise. {club} have changed the game at {home_goals}–{away_goals}.",
		"comment.goal.cross.1":      "{player} attacks the cross and powers the header in for {club}. {home_goals}–{away_goals}.",
		"comment.goal.cross.2":      "A high delivery hangs perfectly; {player} rises above everyone and scores for {club}. {home_goals}–{away_goals}.",
		"comment.goal.cross.3":      "{club} find the wide channel, the ball flashes in, and {player} finishes it at the far post. {home_goals}–{away_goals}.",
		"comment.goal.cutback.1":    "The cut-back is precise, {player} arrives late, and {club} have carved one open. {home_goals}–{away_goals}.",
		"comment.goal.cutback.2":    "{club} work it to the byline; one pass back, one calm touch from {player}, goal. {home_goals}–{away_goals}.",
		"comment.goal.cutback.3":    "{player} reads the pull-back before the defence does and sweeps it in for {club}. {home_goals}–{away_goals}.",
		"comment.goal.through.1":    "A threaded pass splits the line and {player} races clear to score for {club}. {home_goals}–{away_goals}.",
		"comment.goal.through.2":    "{player} bends the run, takes the through ball in stride, and finishes without fuss. {home_goals}–{away_goals}.",
		"comment.goal.through.3":    "{club} slice through the centre; {player} keeps the nerve and rolls it home. {home_goals}–{away_goals}.",
		"comment.goal.long.1":       "{player} lets fly from distance and the shot screams in for {club}. {home_goals}–{away_goals}.",
		"comment.goal.long.2":       "No one closes {player} down, and {club} are rewarded with a thunderous strike. {home_goals}–{away_goals}.",
		"comment.goal.long.3":       "{player} shapes from range, catches it cleanly, and the goalkeeper never gets there. {home_goals}–{away_goals}.",
		"comment.goal.setpiece.1":   "{club} load the set piece into the crowd and {player} gets the decisive touch. {home_goals}–{away_goals}.",
		"comment.goal.setpiece.2":   "The delivery is vicious, {player} muscles through traffic, and the set piece pays off. {home_goals}–{away_goals}.",
		"comment.goal.setpiece.3":   "{player} wins the dead-ball duel and heads {club} onto the scoresheet. {home_goals}–{away_goals}.",
		"comment.goal.scramble.1":   "The ball ricochets around the six-yard box until {player} stabs it in for {club}. {home_goals}–{away_goals}.",
		"comment.goal.scramble.2":   "{club} keep the chance alive through pure pressure, and {player} finally bundles it over the line. {home_goals}–{away_goals}.",
		"comment.goal.scramble.3":   "Nobody clears it, nobody settles it, and {player} reacts first for {club}. {home_goals}–{away_goals}.",
		"comment.goal.counter.1":    "{club} spring forward in three touches and {player} finishes the counter. {home_goals}–{away_goals}.",
		"comment.goal.counter.2":    "The break is ruthless: space, pace, {player}, goal for {club}. {home_goals}–{away_goals}.",
		"comment.goal.counter.3":    "{player} leads the charge, holds off the last challenge, and turns the counter into a goal. {home_goals}–{away_goals}.",
		"comment.chance.1":          "{player} works a chance for {club} but can't finish it.",
		"comment.chance.2":          "Half a chance for {club}'s {player} — dragged wide.",
		"comment.chance.3":          "{club} recycle it through midfield, {player} takes it on early — over the bar.",
		"comment.chance.4":          "{player} goes for power and immediately grabs his head. That had to be better for {club}.",
		"comment.chance.5":          "{club} move it neatly through the centre, {player} shapes to shoot, and the effort skids just past the post.",
		"comment.chance.6":          "{player} darts between two shirts for {club}, but the final touch is heavy and the chance runs away.",
		"comment.chance.7":          "A clever pull-back finds {player}; the stadium draws breath, then groans as the shot rises.",
		"comment.chance.8":          "{club} have numbers forward, {player} chooses the early strike, and the goalkeeper watches it fizz wide.",
		"comment.save.1":            "{player} is denied — a fine stop keeps {club} out.",
		"comment.save.2":            "{player} hits it cleanly for {club}, but the keeper throws up a strong hand.",
		"comment.save.3":            "{player} meets it sweetly, and the goalkeeper gets down sharply to turn {club} away.",
		"comment.save.4":            "{club} think the corner has opened, but {player}'s shot is clawed out at the last moment.",
		"comment.chance.cross.1":    "{club} swing it in early; {player} gets there, but the header loops over.",
		"comment.chance.cross.2":    "A teasing cross finds {player} between markers, yet the contact is never clean.",
		"comment.chance.cross.3":    "{player} attacks the far-post ball for {club}, glancing it just beyond the upright.",
		"comment.save.cross.1":      "{player} meets the cross firmly, and the goalkeeper reacts fast to palm it away.",
		"comment.chance.cutback.1":  "{club} reach the byline and cut it back, but {player} leans over the finish.",
		"comment.chance.cutback.2":  "The pull-back is on a plate for {player}; the shot flashes past the wrong side of the post.",
		"comment.chance.cutback.3":  "{player} arrives late onto the cut-back, only for a defender to crowd the strike.",
		"comment.save.cutback.1":    "A sharp cut-back opens the box, but {player}'s first-time hit is blocked by a strong save.",
		"comment.chance.through.1":  "{player} runs onto the through ball, stretches for the touch, and sends it wide.",
		"comment.chance.through.2":  "{club} split the defence for a second, but {player} cannot bring the pass fully under control.",
		"comment.chance.through.3":  "{player} breaks the line and lifts the effort just too high.",
		"comment.save.through.1":    "{player} is clean through for {club}, but the keeper stays big and wins the duel.",
		"comment.chance.long.1":     "{player} tries one from range for {club}; it swerves late and misses.",
		"comment.chance.long.2":     "The crowd urges {player} to shoot, and the strike whistles over the bar.",
		"comment.chance.long.3":     "{club} settle for the long shot, but {player} cannot keep it down.",
		"comment.save.long.1":       "{player} catches the long-range effort sweetly, forcing the goalkeeper to tip it away.",
		"comment.chance.setpiece.1": "{club} crowd the penalty spot from the set piece, but {player}'s header drifts wide.",
		"comment.chance.setpiece.2": "The dead ball drops into danger; {player} gets a touch, not enough direction.",
		"comment.chance.setpiece.3": "{player} wins the set-piece duel for {club}, though the finish lacks the corner.",
		"comment.save.setpiece.1":   "{player} redirects the set piece on goal, and the keeper claws through bodies to save.",
		"comment.chance.scramble.1": "A scramble breaks out in the box, but {player} cannot force it through the crowd.",
		"comment.chance.scramble.2": "{club} keep the ball alive twice; {player}'s poke is smothered near the line.",
		"comment.chance.scramble.3": "The loose ball falls to {player}, who snatches at it as defenders throw themselves in.",
		"comment.save.scramble.1":   "{player} digs a shot out of the chaos, and the keeper somehow blocks it.",
		"comment.chance.counter.1":  "{club} burst forward on the counter, but {player}'s final touch carries too far.",
		"comment.chance.counter.2":  "{player} has grass ahead and support arriving, yet the early shot skids wide.",
		"comment.chance.counter.3":  "The counter opens beautifully for {club}; {player} just cannot pick the finish.",
		"comment.save.counter.1":    "{player} races clear on the break, but the goalkeeper reads it and makes the stop.",
		"comment.card.yellow":       "Booked — {player} of {club} goes into the book.",
		"comment.card.red":          "Red card! {player} is sent off for {club}.",
		"comment.card.secondyellow": "Second yellow — {player} is off! {club} are down to ten.",
		"comment.injury":            "{player} is down and needs treatment for {club}.",
		"comment.sub":               "{club} make a change: {on} replaces {off}.",
		"comment.sub.fatigue":       "{off} is running on empty — {club} send on {on} in his place.",
		"comment.sub.fresh":         "Fresh legs for {club}: {on} comes on for {off}.",
		"comment.sub.short":         "{player} can't continue — {club} are down to ten men's worth of options and play on short.",
		"comment.quiet.1":           "A quiet spell as the sides feel each other out.",
		"comment.quiet.2":           "The ball pings around midfield with little threat.",
		"comment.quiet.3":           "Patient build-up, but nothing comes of it.",
		"comment.quiet.4":           "The tempo drops for a moment; both benches are watching the shape, not just the ball.",
		"comment.quiet.5":           "Possession changes hands twice in midfield, neither side finding the pass that matters.",
		"comment.quiet.6":           "A spell of cautious passing draws a low murmur from the crowd.",
		"comment.quiet.7":           "The defensive lines hold firm, squeezing the game into the centre circle.",
		"comment.quiet.8":           "The full-backs exchange safe passes while both midfields reset their spacing.",
		"comment.quiet.9":           "A promising angle appears, then disappears as the press closes the lane.",
		"comment.quiet.10":          "Both teams are probing, but the final third remains crowded and awkward.",
		"comment.quiet.11":          "The ball is worked from side to side, more question than threat for now.",
		"comment.quiet.12":          "A heavy touch on halfway lets the defence step out and breathe again.",
		"comment.quiet.13":          "The tempo flickers, then settles back into a careful midfield exchange.",
		"comment.quiet.14":          "One diagonal pass changes the picture briefly before the covering defender tidies up.",
		"comment.quiet.15":          "The crowd senses a pattern forming, but the pass to unlock it never arrives.",
		"comment.halftime":          "Half time: {home_goals}–{away_goals}.",
		"comment.fulltime":          "Full time: {home} {home_goals}–{away_goals} {away}.",
		"comment.shootout":          "Level after 90 minutes — {winner} advance on penalties ({home} {home_pens}–{away_pens} {away}).",
		"comment.adj.push":          "{club} throw caution to the wind and push for it.",

		// MCP UI widgets — human-facing agent-action cards. Chrome +
		// value labels only; numbers/names render as-is. en+ko per FR-35c.
		"widget.badge.observed":           "Observed",
		"widget.badge.decided":            "Decided",
		"widget.badge.read":               "Read",
		"widget.app.mcp_app":              "MCP App",
		"widget.app.waiting":              "Waiting for tool result...",
		"widget.app.problem":              "Problem",
		"widget.app.tool_result":          "tool result",
		"widget.app.incomplete":           "The call did not complete.",
		"widget.focus.free":               "free",
		"widget.focus.spent":              "−{spent} · {balance} left",
		"widget.version":                  "Mindset v{version}",
		"widget.pts":                      "{pts} pts",
		"widget.headline.time":            "Checked the game clock and pacing.",
		"widget.headline.settings":        "Reviewed world settings and game speed.",
		"widget.headline.generic":         "Reviewed the returned game information.",
		"widget.headline.league":          "Reviewed the league standings.",
		"widget.headline.league.results":  "Reviewed recent results.",
		"widget.headline.league.fixtures": "Checked the upcoming fixtures.",
		"widget.headline.league.managers": "Reviewed the division's managers.",
		"widget.headline.disposition":     "Adjusted the manager's disposition.",
		"widget.row.division":             "Division",
		"widget.row.leaders":              "Leaders",
		"widget.row.clubs":                "Clubs",
		"widget.row.results":              "Recent results",
		"widget.row.fixtures":             "Upcoming",
		"widget.row.managers":             "Managers",
		"widget.row.tempo":                "Tempo",
		"widget.row.speed":                "Speed",
		"widget.row.next_match":           "Next match",
		"widget.row.world":                "World",
		"widget.row.run_profile":          "Run profile",
		"widget.row.effective_speed":      "Effective speed",
		"widget.row.league_position":      "League position",
		"widget.row.injuries":             "Injuries",
		"widget.row.expiring_contracts":   "Expiring contracts",
		"widget.section.next_fixture":     "Next fixture",
		"widget.section.last_results":     "Recent results",
		"widget.section.headlines":        "Headlines",
		"widget.section.table":            "Top table",
		"widget.section.results":          "Results",
		"widget.section.fixtures":         "Fixtures",
		"widget.disposition.drifting":     "now {current}, drifting",
		"widget.disposition.applied":      "applied",
		"widget.axis.D1":                  "Risk Appetite",
		"widget.axis.D2":                  "Youth Preference",
		"widget.axis.D3":                  "Playing Identity",
		"widget.axis.D4":                  "Financial Prudence",
		"widget.axis.D5":                  "Loyalty",
		"widget.axis.D6":                  "Discipline",
		"widget.axis.D7":                  "Horizon",
		"widget.axis.D8":                  "Media Posture",
		"widget.axis.D9":                  "Tactical Flexibility",
		"widget.axis.D10":                 "Personal Ambition",

		// MCP UI widgets — observation reads + scout
		"widget.badge.scouted":       "Scouted",
		"widget.headline.situation":  "Checked the dashboard.",
		"widget.headline.news":       "Read the latest press clipping.",
		"widget.headline.news.empty": "Checked the press room; no fresh stories.",
		"widget.row.phase":           "Phase",
		"widget.row.headlines":       "Headlines",
		"widget.headline.club":       "Opened a club dossier.",
		"widget.headline.squad":      "Reviewed the squad sheet.",
		"widget.headline.person":     "Opened a player dossier.",
		"widget.headline.manager":    "Opened a manager dossier.",
		"widget.headline.match":      "Checked a match.",
		"widget.headline.search":     "Searched the player market.",
		"widget.headline.scout":      "Commissioned a scouting report.",
		"widget.row.club":            "Club",
		"widget.row.items":           "New items",
		"widget.row.source":          "Source",
		"widget.row.category":        "Section",
		"widget.row.players":         "Players",
		"widget.row.sample":          "Sample",
		"widget.row.name":            "Name",
		"widget.row.position":        "Position",
		"widget.row.age":             "Age",
		"widget.row.condition":       "Condition",
		"widget.row.board":           "Board",
		"widget.row.fixture":         "Fixture",
		"widget.row.status":          "Status",
		"widget.row.score":           "Score",
		"widget.row.competition":     "Competition",
		"widget.row.found":           "Found",
		"widget.row.top":             "Top result",
		"widget.row.due":             "Report due",
		"widget.match.vs":            "{home} v {away}",
		"widget.match.FINISHED":      "Full time",
		"widget.match.LIVE":          "Live",
		"widget.match.SCHEDULED":     "Scheduled",

		// MCP UI widgets — shaping-write cards (enum values localize via enum.*)
		"widget.headline.priorities":       "Set the priorities.",
		"widget.headline.directive_add":    "Added a directive.",
		"widget.headline.directive_remove": "Removed a directive.",
		"widget.headline.tactical":         "Adjusted the tactical plan.",
		"widget.row.count":                 "Count",
		"widget.row.top_priority":          "Top priority",
		"widget.row.directive":             "Directive",
		"widget.row.active":                "Active directives",
		"widget.row.formation":             "Formation",
		"widget.row.mentality":             "Mentality",
		"widget.row.pressing":              "Pressing",

		// World lifecycle (admin actions surface on the feed — A11)

		// Enum vocabularies: the widget action cards localize
		// mindset enum VALUES through these; a missing entry falls back to the
		// raw token (enumLabel), and the drift test keeps them complete.
		"enum.goal.AVOID_RELEGATION":    "Avoid relegation",
		"enum.goal.WIN_LEAGUE":          "Win the league",
		"enum.goal.WIN_PROMOTION":       "Win promotion",
		"enum.goal.FINISH_TOP_N":        "Finish near the top",
		"enum.goal.CUP_RUN":             "Go on a cup run",
		"enum.goal.DEVELOP_YOUTH":       "Develop the youth",
		"enum.goal.FINANCIAL_HEALTH":    "Keep the finances healthy",
		"enum.goal.BUILD_SQUAD_VALUE":   "Build squad value",
		"enum.goal.ESTABLISH_IDENTITY":  "Establish an identity",
		"enum.goal.PROTECT_JOB":         "Protect the job",
		"enum.goal.FIND_JOB":            "Find a job",
		"enum.verb.START":               "Start",
		"enum.verb.BENCH":               "Bench",
		"enum.verb.EXCLUDE":             "Exclude",
		"enum.verb.ROTATE":              "Rotate",
		"enum.verb.GIVE_MINUTES":        "Give minutes",
		"enum.verb.CAPTAIN":             "Make captain",
		"enum.verb.SIGN":                "Sign",
		"enum.verb.SELL":                "Sell",
		"enum.verb.KEEP":                "Keep",
		"enum.verb.LOAN_OUT":            "Loan out",
		"enum.verb.TARGET_PROFILE":      "Target a profile",
		"enum.verb.RENEW":               "Renew the contract",
		"enum.verb.RELEASE":             "Release",
		"enum.verb.WAGE_CAP":            "Cap wages",
		"enum.verb.DEVELOP":             "Develop",
		"enum.verb.RETRAIN_POSITION":    "Retrain the position",
		"enum.verb.FORBID":              "Forbid",
		"enum.verb.PURSUE_JOB":          "Pursue a job",
		"enum.verb.REJECT_JOB":          "Turn down a job",
		"enum.verb.PUSH_BOARD":          "Push the board",
		"enum.strength.LEAN":            "Lean",
		"enum.strength.INSIST":          "Insist",
		"enum.strength.ABSOLUTE":        "Absolute",
		"enum.mentality.VERY_DEFENSIVE": "Very defensive",
		"enum.mentality.DEFENSIVE":      "Defensive",
		"enum.mentality.BALANCED":       "Balanced",
		"enum.mentality.ATTACKING":      "Attacking",
		"enum.mentality.VERY_ATTACKING": "Very attacking",
		"enum.pressing.LOW":             "Low press",
		"enum.pressing.MID":             "Mid press",
		"enum.pressing.HIGH":            "High press",
		"enum.tempo.SLOW":               "Slow tempo",
		"enum.tempo.MIXED":              "Mixed tempo",
		"enum.tempo.FAST":               "Fast tempo",
		"enum.width.NARROW":             "Narrow",
		"enum.width.MIXED":              "Mixed width",
		"enum.width.WIDE":               "Wide",
		"enum.directness.SHORT":         "Short passing",
		"enum.directness.MIXED":         "Mixed passing",
		"enum.directness.DIRECT":        "Direct passing",

		"feed.world.started": "The world is running.",
		"feed.world.paused":  "The world is paused for maintenance.",
		"feed.world.resumed": "The world has resumed.",

		// API error surfaces (rendered per request locale)
		"error.bad_request":                             "Invalid request.",
		"error.unknown_tier":                            "No such division.",
		"error.unknown_club":                            "No such club.",
		"error.not_found":                               "Not found.",
		"error.internal":                                "Internal server error.",
		"error.admin_required":                          "Admin Token required.",
		"error.conflict":                                "The request conflicts with the world's current state.",
		"error.runtime_settings.game_speed":             "Game speed must be one of 5, 15, 30, or 60.",
		"error.runtime_settings.idle_acceleration":      "Idle acceleration must be between 2 and 64.",
		"error.runtime_settings.offseason_acceleration": "Off-season acceleration must be between 2 and 240.",
		"error.streaming_unsupported":                   "Streaming is not supported on this connection.",

		// MCP error surface (docs/11 §1.2; English-only on the wire, but
		// every key ships both locales — CLAUDE.md hard rule)
		"err.auth_required":      "A Manager Token is required.",
		"err.invalid_token":      "Unknown or replaced Manager Token.",
		"err.manager_retired":    "This Manager has retired.",
		"err.focus.insufficient": "Needs {required} FP, balance is {balance}.",
		"err.not_found":          "Not found: {id}.",
		"err.invalid_target":     "The target does not fit this verb.",
		"err.conflict":           "Conflicts with active directive {with}.",
		"err.cap_exceeded":       "Cap exceeded.",
		"err.unemployed_scope":   "Requires employment at a club.",
		"err.validation":         "Invalid request: {detail}",

		// Reputation & mood descriptors (FR-22a hidden → observable)
		"desc.reputation.OBSCURE":     "Obscure",
		"desc.reputation.LOCAL":       "Local",
		"desc.reputation.REGIONAL":    "Regional",
		"desc.reputation.NATIONAL":    "National",
		"desc.reputation.CONTINENTAL": "Continental",
		"desc.reputation.WORLDWIDE":   "Worldwide",
		"desc.mood.STEADY":            "Steady",

		// Player personality descriptors (docs/08 §5, FR-22a)
		"desc.player.CONSUMMATE_PROFESSIONAL": "Consummate professional",
		"desc.player.DRIVEN":                  "Driven",
		"desc.player.TEAM_HEART":              "Heart of the team",
		"desc.player.IRON_NERVED":             "Iron-nerved",
		"desc.player.MERCENARY":               "Mercenary",
		"desc.player.VOLATILE":                "Volatile",
		"desc.player.GLASS_CANNON":            "Glass cannon",
		"desc.player.HOMEBODY":                "Homebody",
		"desc.player.WALLFLOWER":              "Wallflower",
		"desc.player.BALANCED":                "Balanced character",

		// Board / club Descriptors
		"desc.confidence.HIGH":         "Confident",
		"desc.confidence.MODERATE":     "Watchful",
		"desc.confidence.LOW":          "Restless",
		"desc.injury.DAYS":             "A knock — out for days",
		"desc.injury.WEEKS":            "Injured — weeks out",
		"desc.injury.MONTH":            "A long lay-off — a month or more",
		"desc.form.IN_FORM":            "In form",
		"desc.form.STEADY":             "Steady",
		"desc.form.OUT_OF_FORM":        "Out of form",
		"desc.form.UNKNOWN":            "Untested",
		"desc.security.SECURE":         "Secure",
		"desc.security.STABLE":         "Stable",
		"desc.security.UNDER_PRESSURE": "Under pressure",
		"desc.facility.EXCELLENT":      "Excellent",
		"desc.facility.GOOD":           "Good",
		"desc.facility.ADEQUATE":       "Adequate",
		"desc.facility.POOR":           "Poor",

		// Manager style Descriptors (public reads on their football)
		"desc.style.IDEALIST":    "Attacking idealist",
		"desc.style.PRAGMATIST":  "Results-first pragmatist",
		"desc.style.FIREFIGHTER": "Survival specialist",
		"desc.style.TRADER":      "Market operator",
		"desc.style.PROFESSOR":   "System purist",
		"desc.style.MOTIVATOR":   "Man-manager",
		"desc.style.TYRANT":      "Iron disciplinarian",
		"desc.style.GAMBLER":     "High-risk gambler",

		// Scout evidence: behavioral impressions keyed per hidden attribute +
		// direction (docs/11 §4/§5, FR-22). The prose carries the valence — it
		// never names the attribute or its value.
		"evidence.professionalism.high":  "Trains with total dedication.",
		"evidence.professionalism.low":   "Casual about training and preparation.",
		"evidence.ambition.high":         "Burns to reach the top.",
		"evidence.ambition.low":          "Comfortable where they are, short on drive.",
		"evidence.loyalty.high":          "Deeply attached to their club.",
		"evidence.loyalty.low":           "Ready to move on for the right offer.",
		"evidence.temperament.high":      "Keeps a cool head under provocation.",
		"evidence.temperament.low":       "Quick to boil over.",
		"evidence.pressure.high":         "Thrives when the heat is on.",
		"evidence.pressure.low":          "Tightens up when the pressure mounts.",
		"evidence.adaptability.high":     "Settles into new surroundings fast.",
		"evidence.adaptability.low":      "Slow to settle somewhere new.",
		"evidence.sociability.high":      "A popular figure in the dressing room.",
		"evidence.sociability.low":       "Keeps to themselves around the squad.",
		"evidence.influence.high":        "A natural leader others look to.",
		"evidence.influence.low":         "Content to follow, not to lead.",
		"evidence.consistency.high":      "Turns it in week after week.",
		"evidence.consistency.low":       "Blows hot and cold from game to game.",
		"evidence.big_match_nerve.high":  "Rises to the big occasion.",
		"evidence.big_match_nerve.low":   "Shrinks when the stakes are highest.",
		"evidence.injury_proneness.high": "Prone to picking up knocks.",
		"evidence.injury_proneness.low":  "Remarkably durable.",
		"evidence.recovery.high":         "Bounces back quickly from exertion.",
		"evidence.recovery.low":          "Slow to recover between outings.",
		"evidence.discipline.high":       "Keeps it clean and disciplined.",
		"evidence.discipline.low":        "Rash, and no stranger to the referee's book.",
		"evidence.versatility.high":      "Comfortable in a range of roles.",
		"evidence.versatility.low":       "A specialist in one role only.",

		// News (docs/11 §4/§5)
		"news.scout.report":                  "Scouting report on {player} is in (depth {level}).",
		"news.decision.shift":                "{manager} ({club}) is reshaping their approach.",
		"news.transfer.completed":            "{player} joins {club} as a free agent.",
		"news.transfer.fee_completed":        "{club} sign {player} from {from}.",
		"news.board.warning":                 "{club}'s board issues a private warning to the manager.",
		"news.board.ultimatum":               "{club}'s board delivers a public ultimatum to the manager.",
		"news.board.reprieve":                "{club}'s manager wins a reprieve as board confidence recovers.",
		"news.board.sacked":                  "{manager} is sacked by {club}.",
		"news.board.caretaker":               "{manager} takes over as {club}'s caretaker manager.",
		"news.board.appointed":               "{club} appoint {manager} as their new manager.",
		"news.board.caretaker_permanent":     "{club} confirm caretaker {manager} as their permanent manager.",
		"news.board.retired":                 "{manager} announces their retirement.",
		"news.youth.intake":                  "{club} welcome {count} new prospects from the academy.",
		"news.youth.graduated":               "{club} promote {count} academy graduates to the senior squad.",
		"news.player.retired":                "{player} of {club} hangs up their boots.",
		"news.player.retired_free":           "{player} calls time on their playing career.",
		"news.contract.renewed":              "{club} tie down {count} players on fresh terms.",
		"news.contract.lapsed":               "{count} players leave {club} as their contracts expire.",
		"news.injury.days":                   "{player} picks up a knock and will miss a few days for {club}.",
		"news.injury.weeks":                  "{player} is injured and faces weeks out for {club}.",
		"news.injury.month":                  "Blow for {club}: {player} is facing a month or more on the sidelines.",
		"news.article.source.transfer":       "Transfer Wire",
		"news.article.source.match":          "Match Centre",
		"news.article.source.injury":         "Medical Bulletin",
		"news.article.source.board":          "Club Desk",
		"news.article.source.decision":       "Training Ground",
		"news.article.source.career":         "League Wire",
		"news.article.source.youth":          "Academy Desk",
		"news.article.source.contract":       "Contract Desk",
		"news.article.source.scout":          "Scouting Office",
		"news.article.source.media":          "Kaiserbruck Gazette",
		"news.article.deck.transfer":         "The market has moved again as clubs continue to reshape their squads.",
		"news.article.deck.match":            "The final whistle brought another turn in the league story.",
		"news.article.deck.matchday.preview": "The fixture list has been gathered into one matchday briefing.",
		"news.article.deck.matchday.results": "The day's scores are in, and the table has a new shape.",
		"news.article.deck.injury":           "A fitness concern is set to affect selection plans.",
		"news.article.deck.board":            "Boardroom pressure has produced a fresh development.",
		"news.article.deck.decision":         "The manager's latest shift points to a changing approach.",
		"news.article.deck.career":           "A career decision has changed the managerial landscape.",
		"news.article.deck.youth":            "The academy pipeline has delivered its latest update.",
		"news.article.deck.contract":         "Contract business has changed the squad picture.",
		"news.article.deck.scout":            "A private scouting file has been delivered to the manager.",
		"news.article.deck.media":            "The latest item from around the league has landed.",
		"news.article.body.transfer":         "{headline}\n\nThe move has already changed the temperature around the market. Recruitment staff at rival clubs are expected to re-check their shortlists, while supporters will watch closely to see whether this is a one-off move or the first part of a wider reshuffle.\n\nInside the division, the immediate question is squad balance: who gains minutes, who loses them, and which manager now feels pressured to answer.",
		"news.article.body.match":            "{headline}\n\nThe final whistle did more than settle the score. It moved the table, nudged the form guide, and gave both dressing rooms something concrete to carry into the next training week.\n\nFor the winners it is another line of evidence that the plan is taking hold. For the beaten side, the review will focus on where the decisive moments slipped away.",
		"news.article.body.matchday.preview": "{headline}\n\nFixtures:\n{fixtures}\n\nOpening fixture: {spotlight}. The schedule gives every manager the same problem in a different accent: protect the shape, find the first punch, and avoid turning a difficult afternoon into a week-long story.\n\nBy the next round-up, the table may look familiar or it may have shifted under everyone. The opening whistle will decide which clubs get to talk about plans and which ones have to explain damage.",
		"news.article.body.matchday.results": "{headline}\n\nResults:\n{results}\n\nTable picture:\n{table}\n\nStoryline: {story}.\n\nThe scores do not stand alone. Each one tugs at form, confidence, and the next team talk. Winners leave with proof, beaten sides leave with film to study, and the clubs caught in between must decide whether the day was a warning or just noise.",
		"news.article.body.injury":           "{headline}\n\nMedical staff will keep the situation under review, but selection plans already have to adjust. The next squad sheet may reveal whether the manager trusts the depth chart or reshapes the plan to protect the remaining legs.\n\nSupporters will hope the absence is brief; opponents will notice the gap immediately.",
		"news.article.body.board":            "{headline}\n\nThe development lands with the season still moving, and every result from here will be read through the same pressure gauge. Board confidence rarely turns on one sentence, but it can turn quickly once supporters sense uncertainty.\n\nThe dugout now needs performances that quiet the room as much as points that move the table.",
		"news.article.body.decision":         "{headline}\n\nThe change should show up first in selection, then in the rhythm of matches: who starts, who is protected, and where the manager chooses to spend risk.\n\nAround the training ground, the message is clear enough. The next few fixtures will test whether the idea is conviction or experiment.",
		"news.article.body.career":           "{headline}\n\nA managerial move always shifts more than one office door. Players read it, boards compare it, and unemployed coaches quietly revise the list of jobs that may soon open.\n\nFor supporters, the story is simpler: a new voice, a changed touchline, and fresh expectations before the next whistle.",
		"news.article.body.youth":            "{headline}\n\nThe academy staff will be judged on patience as much as promise. Some of these names may need seasons before they matter to the first team, but the best clubs build those stories long before the crowd learns them.\n\nFor now, coaches will track attitude, physical growth, and how quickly the prospects absorb senior standards.",
		"news.article.body.contract":         "{headline}\n\nContract work rarely produces noise on match day, but it shapes the room every week. Wage space, squad depth, and summer flexibility all change when a club decides who stays tied to the project.\n\nThe next market window will show whether this was housekeeping or preparation for something larger.",
		"news.article.body.scout":            "{headline}\n\nThe file adds another layer of evidence for recruitment and selection meetings. Good scouting does not make the decision by itself; it narrows the risk and tells the manager which questions still need watching.\n\nThe next move is whether to revisit the player, act quickly, or fold the report into a broader search.",
		"news.article.body.media":            "{headline}\n\nAround the league, stories like this rarely stay isolated for long. A small development in one camp can become pressure in another once boards, supporters, and managers start comparing direction.\n\nFurther details will matter, but the signal is already part of the week’s conversation.",

		// Shared terms
		"term.free_agent":                   "Free agent",
		"term.window.summer":                "summer",
		"term.window.winter":                "winter",
		"term.competition.LEAGUE":           "League",
		"term.competition.CUP":              "Cup",
		"term.matchday.fixture_line":        "Round {round}: {home} v {away}",
		"term.matchday.fixture_spotlight":   "{home} v {away}",
		"term.matchday.result_line":         "{home} {home_goals}-{away_goals} {away}",
		"term.matchday.result_line.winner":  "{home} {home_goals}-{away_goals} {away}; {winner} advance",
		"term.matchday.table_leader":        "Division {division}: {club} lead on {points} pts",
		"term.matchday.table_cup":           "Cup ties reshaped the bracket rather than the league table",
		"term.matchday.story_margin":        "Biggest margin: {best_home} {home_goals}-{away_goals} {best_away}",
		"term.matchday.story_draws":         "Draws: {draws}",
		"term.matchday.story_all_winners":   "No draw softened the table movement",
		"term.matchday.story_unavailable":   "Storyline data was unavailable for this round-up",
		"term.chance_type.CROSS_HEADER":     "Cross headers",
		"term.chance_type.CUTBACK":          "Cutbacks",
		"term.chance_type.THROUGH_BALL":     "Through balls",
		"term.chance_type.LONG_SHOT":        "Long shots",
		"term.chance_type.SET_PIECE_HEADER": "Set-piece headers",
		"term.chance_type.SCRAMBLE":         "Box scrambles",
		"term.chance_type.COUNTER":          "Counters",
		"term.quality.HIGH":                 "High",
		"term.quality.MEDIUM":               "Medium",
		"term.quality.LOW":                  "Low",
		"term.tempo.MATCH":                  "Match",
		"term.tempo.IDLE":                   "Idle",
		"term.tempo.OFFSEASON":              "Off-season",
		"term.tempo.PAUSED":                 "Paused",
		"term.state.ready":                  "Ready",
		"term.state.running":                "Running",
		"term.state.paused":                 "Paused",

		// Positional familiarity descriptors (docs/08 §2)
		"desc.familiarity.NATURAL":      "Natural",
		"desc.familiarity.ACCOMPLISHED": "Accomplished",
		"desc.familiarity.COMPETENT":    "Competent",
		"desc.familiarity.AWKWARD":      "Awkward",
		"desc.weak_foot.STRONG":         "Strong",
		"desc.weak_foot.USEFUL":         "Useful",
		"desc.weak_foot.LIMITED":        "Limited",
		"desc.weak_foot.ONE_FOOTED":     "One-footed",

		// Visible attribute display names (docs/08 §2)
		"attr.FINISHING":       "Finishing",
		"attr.LONG_SHOTS":      "Long Shots",
		"attr.FIRST_TOUCH":     "First Touch",
		"attr.PASSING":         "Passing",
		"attr.CROSSING":        "Crossing",
		"attr.DRIBBLING":       "Dribbling",
		"attr.TECHNIQUE":       "Technique",
		"attr.HEADING":         "Heading",
		"attr.TACKLING":        "Tackling",
		"attr.MARKING":         "Marking",
		"attr.SET_PIECES":      "Set Pieces",
		"attr.AGGRESSION":      "Aggression",
		"attr.VISION":          "Vision",
		"attr.DECISIONS":       "Decisions",
		"attr.COMPOSURE":       "Composure",
		"attr.CONCENTRATION":   "Concentration",
		"attr.POSITIONING":     "Positioning",
		"attr.OFF_BALL":        "Off the Ball",
		"attr.ANTICIPATION":    "Anticipation",
		"attr.WORK_RATE":       "Work Rate",
		"attr.BRAVERY":         "Bravery",
		"attr.TEAMWORK":        "Teamwork",
		"attr.LEADERSHIP":      "Leadership",
		"attr.DETERMINATION":   "Determination",
		"attr.FLAIR":           "Flair",
		"attr.ACCELERATION":    "Acceleration",
		"attr.PACE":            "Pace",
		"attr.AGILITY":         "Agility",
		"attr.BALANCE":         "Balance",
		"attr.STRENGTH":        "Strength",
		"attr.STAMINA":         "Stamina",
		"attr.NATURAL_FITNESS": "Natural Fitness",
		"attr.JUMPING_REACH":   "Jumping Reach",
		"attr.REFLEXES":        "Reflexes",
		"attr.ONE_ON_ONES":     "One on Ones",
		"attr.HANDLING":        "Handling",
		"attr.AERIAL_REACH":    "Aerial Reach",
		"attr.COMMAND_OF_AREA": "Command of Area",
		"attr.COMMUNICATION":   "Communication",
		"attr.DISTRIBUTION":    "Distribution",
		"attr.SWEEPING":        "Sweeping",
		"attr.ECCENTRICITY":    "Eccentricity",
		"attr.PUNCHING":        "Punching",
		"attr.DEFENDING":       "Defending",
		"attr.AERIAL":          "Aerial",
		"attr.SHOT_STOPPING":   "Shot Stopping",
		"attr.AERIAL_COMMAND":  "Aerial Command",

		// Console UI chrome (served via /v1/ui — the Console stays
		// catalog-free, docs/07 §6)
		"ui.app.title":                                 "Agentic FC",
		"ui.tab.media":                                 "Media",
		"ui.tab.table":                                 "Table",
		"ui.tab.clubs":                                 "Clubs",
		"ui.tab.fixtures":                              "Fixtures/Results",
		"ui.tab.admin_settings":                        "Settings",
		"ui.col.pos":                                   "Pos",
		"ui.col.club":                                  "Club",
		"ui.col.div":                                   "Div",
		"ui.col.security":                              "Security",
		"ui.col.source":                                "Source",
		"ui.col.article":                               "Article",
		"ui.col.name":                                  "Name",
		"ui.col.age":                                   "Age",
		"ui.col.position":                              "Pos",
		"ui.col.attributes":                            "Attributes",
		"ui.col.contract":                              "Contract",
		"ui.col.played":                                "P",
		"ui.col.won":                                   "W",
		"ui.col.drawn":                                 "D",
		"ui.col.lost":                                  "L",
		"ui.col.gf":                                    "GF",
		"ui.col.ga":                                    "GA",
		"ui.col.pts":                                   "Pts",
		"ui.col.round":                                 "Rd",
		"ui.col.kickoff":                               "Kick-off",
		"ui.col.fixture":                               "Fixture",
		"ui.col.status":                                "Status",
		"ui.table.live":                                "Live standings",
		"ui.fixtures.empty":                            "No fixtures or results to show.",
		"ui.fixture.live":                              "Live",
		"ui.fixture.scheduled":                         "Soon",
		"ui.fixture.result":                            "Result",
		"ui.fixture.replay":                            "Replay",
		"ui.fixture.archived":                          "Archive",
		"ui.fixture.scheduled_notice":                  "Match has not kicked off yet.",
		"ui.match.none":                                "No match in progress — the grounds are quiet.",
		"ui.match.loading":                             "Loading match detail...",
		"ui.match.legend":                              "G goal · o chance · x card · + injury · s sub · ! shootout",
		"ui.match.scoreboard":                          "Scoreboard",
		"ui.match.goalflash":                           "GOAL",
		"ui.match.live":                                "Live match",
		"ui.match.ended":                               "Match finished — replay will appear in results.",
		"ui.match.waiting_result":                      "Full time is being recorded. Waiting for the result ledger...",
		"ui.match.modal.close":                         "Esc close · ←/→ other live matches",
		"ui.match.modal.replay_help":                   "Esc close · PgUp/PgDn or ←/→ rewind/advance",
		"ui.match.stats":                               "Match stats",
		"ui.match.ratings":                             "Ratings",
		"ui.match.latest":                              "Latest scores",
		"ui.match.momentum":                            "Momentum",
		"ui.match.away":                                "Away",
		"ui.match.winner":                              "Winner",
		"ui.match.scorers":                             "Scorers",
		"ui.match.cards":                               "Cards",
		"ui.match.subs":                                "Substitutions",
		"ui.match.replay":                              "Replay log",
		"ui.match.replay.more":                         "PageDown for more replay lines.",
		"ui.match.replay.archived":                     "Archived result: commentary replay was not preserved.",
		"ui.match.stat.shots":                          "Shots",
		"ui.match.stat.cards":                          "Cards",
		"ui.match.stat.subs":                           "Subs",
		"ui.match.stat.chance_mix":                     "Chance mix",
		"ui.match.stat.quality":                        "Shot quality",
		"ui.match.stat.aerial":                         "Aerial",
		"ui.match.stat.press":                          "Press",
		"ui.match.stat.setpieces":                      "Set pieces",
		"ui.header.division":                           "Division {tier}",
		"ui.help.keys":                                 "1 Media · 2 Table · 3 Clubs · 4 Results · Enter/Space/click opens live/replay · ←/→ live matches/replay · Esc close · PgUp/PgDn replay · q quit",
		"ui.help.keys_admin":                           "1 Media · 2 Table · 3 Clubs · 4 Results · 5 Settings · +/- or [/] adjust · ↑/↓ select · q quit",
		"ui.admin.token_required":                      "Admin token required.",
		"ui.admin.settings.loading":                    "Loading settings...",
		"ui.admin.settings.title":                      "Runtime Settings",
		"ui.admin.settings.help":                       "Use ↑/↓ to select a pacing setting, then +/- or [/ ] to adjust it live.",
		"ui.admin.settings.setting":                    "Setting",
		"ui.admin.settings.value":                      "Value",
		"ui.admin.settings.allowed":                    "Allowed",
		"ui.admin.settings.game_speed":                 "Game speed",
		"ui.admin.settings.idle_acceleration":          "Idle acceleration",
		"ui.admin.settings.offseason_acceleration":     "Off-season acceleration",
		"ui.admin.settings.determinism":                "Determinism",
		"ui.admin.settings.determinism_body":           "Runtime pacing only changes wall-clock delay; game-time ordering and outcomes are unchanged.",
		"ui.admin.settings.rebuild_required":           "Still requires a new world",
		"ui.admin.settings.rebuild.seed":               "seed",
		"ui.admin.settings.rebuild.divisions":          "divisions",
		"ui.admin.settings.rebuild.clubs_per_division": "clubs per division",
		"ui.admin.settings.rebuild.quality":            "world quality",
		"ui.admin.settings.rebuild.economy":            "economy",
		"ui.admin.settings.rebuild.culture_mix":        "name culture mix",
		"ui.admin.settings.saved":                      "Runtime settings updated.",
		"ui.terminal.too_small":                        "Terminal too small — need at least {min_cols}×{min_rows} (now {cols}×{rows}).",
		"ui.mode.viewer":                               "Viewer",
		"ui.mode.admin":                                "Admin",
		"ui.feed.waiting":                              "Waiting for the world…",
		"ui.notice.news":                               "Fresh story: {title}",
		"ui.notice.match":                              "{count} live match window(s) just opened.",
		"ui.media.empty":                               "No press items yet — waiting for the first story.",
		"ui.media.recent":                              "Recent press",
		"ui.clubs.empty":                               "No club data available.",
		"ui.club.caretaker":                            "Caretaker appointment",
		"ui.club.manager":                              "Manager",
		"ui.club.predicted":                            "Predicted",
		"ui.club.objective":                            "Objective",
		"ui.club.confidence":                           "Board",
		"ui.club.security":                             "Job",
		"ui.club.fan_mood":                             "Fans",
		"ui.club.balance":                              "Balance",
		"ui.club.wage_bill":                            "Wages",
		"ui.club.transfer_budget":                      "Transfer",
		"ui.club.squad":                                "Squad",
		"ui.player.empty":                              "No player selected.",
		"ui.player.dossier":                            "Player dossier",
		"ui.player.group":                              "Unit",
		"ui.player.body":                               "Body",
		"ui.player.foot":                               "Foot",
		"ui.player.familiarity":                        "Familiarity",
		"ui.player.profile":                            "Attribute profile",
		"ui.player.youth":                              "Academy player",
		"ui.error.prefix":                              "Problem:",
		"ui.clock":                                     "{month} {day}, {hh}:{mm} · Season {season}",
		"ui.month.1":                                   "Jan",
		"ui.month.2":                                   "Feb",
		"ui.month.3":                                   "Mar",
		"ui.month.4":                                   "Apr",
		"ui.month.5":                                   "May",
		"ui.month.6":                                   "Jun",
		"ui.month.7":                                   "Jul",
		"ui.month.8":                                   "Aug",
		"ui.month.9":                                   "Sep",
		"ui.month.10":                                  "Oct",
		"ui.month.11":                                  "Nov",
		"ui.month.12":                                  "Dec",
	},

	LocaleKO: {
		// Live feed
		"feed.drift.grew":       "{player} ({club}) 성장세 — {attr} {from} → {to}.",
		"feed.drift.declined":   "{player} ({club}) 하락세 — {attr} {from} → {to}.",
		"feed.window.opened":    "{window} 이적시장이 열렸습니다.",
		"feed.window.closed":    "{window} 이적시장이 마감되었습니다.",
		"feed.season.ended":     "시즌 {season} 종료 — 한 해가 저물었습니다.",
		"feed.match.kickoff":    "킥오프: {home} vs {away} ({competition} {round}라운드).",
		"feed.match.result":     "경기 종료: {home} {home_goals}–{away_goals} {away} ({competition}).",
		"feed.cup.result":       "컵: {home} {home_goals}–{away_goals} {away} — {winner} 진출.",
		"feed.matchday.preview": "매치데이 프리뷰: {month}월 {day}일 {kickoff_time}, {count}경기가 예정되어 있습니다.",
		"feed.matchday.results": "매치데이 라운드업: {kickoff_time} 창의 {count}경기 결과가 정리됐습니다.",
		"feed.cup.champion":     "{club}, 컵 우승 — 시즌 {season}의 챔피언입니다!",

		// 라이브 경기 코멘터리 (docs/02 §4)
		"comment.kickoff":           "{home} 대 {away}, 경기가 시작됐습니다.",
		"comment.goal.1":            "골! {player}, {club}의 골망을 흔듭니다 — {home_goals}–{away_goals}.",
		"comment.goal.2":            "{player} 득점! {club} 환호합니다 — {home_goals}–{away_goals}.",
		"comment.goal.3":            "들어갔습니다! {player}, {club}를 위해 득점. {home_goals}–{away_goals}.",
		"comment.goal.4":            "{player}, 강하게 꽂아 넣습니다! {club} 관중석이 폭발합니다 — {home_goals}–{away_goals}.",
		"comment.goal.5":            "{player}의 냉정한 마무리. {club}, 마침내 균열을 냅니다 — {home_goals}–{away_goals}.",
		"comment.goal.6":            "{player}, 침투 타이밍이 완벽합니다. 한 번 보고 마무리, {club} 득점 — {home_goals}–{away_goals}.",
		"comment.goal.7":            "순식간에 공간이 열립니다 — {player} 달려들어 꽂아 넣고 {club} 벤치가 튀어 오릅니다. {home_goals}–{away_goals}.",
		"comment.goal.8":            "{player}, 망설임이 없습니다. 첫 터치, 슛, 함성. {club}, 경기 흐름을 바꿉니다 — {home_goals}–{away_goals}.",
		"comment.goal.cross.1":      "{player}, 크로스를 향해 뛰어올라 강한 헤더로 {club} 득점! {home_goals}–{away_goals}.",
		"comment.goal.cross.2":      "높은 크로스가 완벽하게 걸립니다. {player}가 모두 위에서 찍어 넣습니다 — {club} 득점, {home_goals}–{away_goals}.",
		"comment.goal.cross.3":      "{club}, 측면을 열고 빠른 공을 넣습니다. 먼 포스트의 {player} 마무리! {home_goals}–{away_goals}.",
		"comment.goal.cutback.1":    "정확한 컷백, 늦게 들어온 {player}, 그리고 {club}의 깔끔한 득점입니다. {home_goals}–{away_goals}.",
		"comment.goal.cutback.2":    "{club}, 골라인까지 파고든 뒤 뒤로 내줍니다. {player} 한 번 잡고 침착하게 골. {home_goals}–{away_goals}.",
		"comment.goal.cutback.3":    "{player}, 수비보다 먼저 컷백을 읽고 밀어 넣습니다. {club} 득점 — {home_goals}–{away_goals}.",
		"comment.goal.through.1":    "스루패스가 수비 라인을 가릅니다. {player}가 빠져나가 {club} 득점! {home_goals}–{away_goals}.",
		"comment.goal.through.2":    "{player}, 침투 각도를 만들고 패스를 받아 그대로 마무리합니다. {home_goals}–{away_goals}.",
		"comment.goal.through.3":    "{club}, 중앙을 단숨에 찢습니다. {player} 흔들리지 않고 굴려 넣습니다 — {home_goals}–{away_goals}.",
		"comment.goal.long.1":       "{player}, 먼 거리에서 과감하게 때립니다. 공이 그대로 꽂힙니다! {club} 득점 — {home_goals}–{away_goals}.",
		"comment.goal.long.2":       "아무도 {player}를 막지 않습니다. {club}, 강렬한 중거리포로 보상받습니다 — {home_goals}–{away_goals}.",
		"comment.goal.long.3":       "{player}, 거리에서 자세를 잡고 제대로 맞힙니다. 골키퍼가 닿지 못합니다 — {home_goals}–{away_goals}.",
		"comment.goal.setpiece.1":   "{club}, 세트피스를 박스 안에 밀어 넣고 {player}가 결정적인 터치를 가져갑니다. {home_goals}–{away_goals}.",
		"comment.goal.setpiece.2":   "날카로운 킥, 몸싸움을 뚫은 {player}, 세트피스가 통합니다. {home_goals}–{away_goals}.",
		"comment.goal.setpiece.3":   "{player}, 데드볼 경합을 이기고 헤더 득점. {club}이 점수판을 움직입니다 — {home_goals}–{away_goals}.",
		"comment.goal.scramble.1":   "공이 골문 앞에서 튕깁니다. {player}가 끝내 찔러 넣습니다 — {club} 득점, {home_goals}–{away_goals}.",
		"comment.goal.scramble.2":   "{club}, 압박으로 기회를 살려 둡니다. 마지막에는 {player}가 몸으로 밀어 넣습니다. {home_goals}–{away_goals}.",
		"comment.goal.scramble.3":   "누구도 걷어내지 못한 공, 가장 빨리 반응한 건 {player}입니다. {club} 득점 — {home_goals}–{away_goals}.",
		"comment.goal.counter.1":    "{club}, 세 번의 터치로 역습을 완성합니다. {player} 마무리 — {home_goals}–{away_goals}.",
		"comment.goal.counter.2":    "잔인할 만큼 빠른 역습입니다. 공간, 속도, {player}, 골. {club} 득점 — {home_goals}–{away_goals}.",
		"comment.goal.counter.3":    "{player}, 역습을 이끌고 마지막 도전을 버텨 득점으로 바꿉니다. {home_goals}–{away_goals}.",
		"comment.chance.1":          "{player}, {club}의 기회를 만들지만 마무리가 아쉽습니다.",
		"comment.chance.2":          "{club} {player}의 절반의 기회 — 옆그물을 스칩니다.",
		"comment.chance.3":          "{club}, 중원에서 공을 돌리다 {player}가 과감하게 슛 — 골대 위로 뜹니다.",
		"comment.chance.4":          "{player}, 힘으로 밀어붙이지만 곧바로 머리를 감싸쥡니다. {club}로서는 아쉬운 장면입니다.",
		"comment.chance.5":          "{club}, 중앙에서 깔끔하게 풀어냅니다. {player} 슈팅 자세 — 공은 골대 옆으로 살짝 빗나갑니다.",
		"comment.chance.6":          "{player}, 수비 둘 사이를 파고듭니다. 하지만 마지막 터치가 길어 {club}의 기회가 흘러갑니다.",
		"comment.chance.7":          "영리한 컷백이 {player}에게 갑니다. 경기장이 숨을 삼키지만 슛은 높게 뜹니다.",
		"comment.chance.8":          "{club}, 전방 숫자가 많습니다. {player}가 빠른 슛을 선택하고, 골키퍼는 공이 옆으로 흐르는 걸 지켜봅니다.",
		"comment.save.1":            "{player} 막힙니다 — 멋진 선방이 {club}를 좌절시킵니다.",
		"comment.save.2":            "{player}, {club}의 슛을 제대로 때렸지만 골키퍼가 강한 손으로 쳐냅니다.",
		"comment.save.3":            "{player} 제대로 맞혔습니다. 골키퍼가 낮게 몸을 던져 {club}의 득점을 막아냅니다.",
		"comment.save.4":            "{club}, 구석이 열린 줄 알았습니다. 그러나 {player}의 슛이 마지막 순간 걷어 올려집니다.",
		"comment.chance.cross.1":    "{club}, 이른 크로스를 올립니다. {player}가 닿았지만 헤더는 위로 뜹니다.",
		"comment.chance.cross.2":    "까다로운 크로스가 수비 사이의 {player}에게 갑니다. 하지만 제대로 맞지 않습니다.",
		"comment.chance.cross.3":    "{player}, 먼 포스트로 넘어온 공을 향해 달려들지만 살짝 빗나갑니다.",
		"comment.save.cross.1":      "{player}가 크로스를 강하게 맞혔지만 골키퍼가 빠르게 반응해 쳐냅니다.",
		"comment.chance.cutback.1":  "{club}, 골라인까지 파고들어 컷백을 내줍니다. {player}의 슛은 뜹니다.",
		"comment.chance.cutback.2":  "{player}에게 완벽한 컷백이 왔지만, 슛은 골대 바깥으로 스쳐 갑니다.",
		"comment.chance.cutback.3":  "{player}, 늦게 들어와 컷백을 받지만 수비가 끝까지 압박합니다.",
		"comment.save.cutback.1":    "날카로운 컷백이 박스를 엽니다. {player}의 논스톱 슛은 골키퍼 선방에 막힙니다.",
		"comment.chance.through.1":  "{player}, 스루패스를 따라 들어가지만 마지막 터치가 길어 옆으로 흐릅니다.",
		"comment.chance.through.2":  "{club}, 순간적으로 수비를 가르지만 {player}가 공을 완전히 잡아두지 못합니다.",
		"comment.chance.through.3":  "{player}, 라인을 깨고 들어가 띄워 차지만 너무 높습니다.",
		"comment.save.through.1":    "{player}, {club}의 완벽한 일대일 기회. 그러나 골키퍼가 크게 버티며 막아냅니다.",
		"comment.chance.long.1":     "{player}, 거리에서 시도합니다. 공은 막판에 휘며 벗어납니다.",
		"comment.chance.long.2":     "관중이 슛을 외치고 {player}가 때립니다. 공은 골대 위를 스칩니다.",
		"comment.chance.long.3":     "{club}, 중거리 슛을 택하지만 {player}가 낮게 누르지 못합니다.",
		"comment.save.long.1":       "{player}, 중거리 슛을 제대로 맞혔고 골키퍼가 손끝으로 밀어냅니다.",
		"comment.chance.setpiece.1": "{club}, 세트피스로 골문 앞을 붐비게 하지만 {player}의 헤더는 옆으로 갑니다.",
		"comment.chance.setpiece.2": "데드볼이 위험 지역에 떨어집니다. {player}가 건드렸지만 방향이 부족합니다.",
		"comment.chance.setpiece.3": "{player}, 세트피스 경합을 이겼지만 마무리는 구석을 찾지 못합니다.",
		"comment.save.setpiece.1":   "{player}가 세트피스를 골문으로 돌려놓고, 골키퍼가 몸들 사이로 걷어냅니다.",
		"comment.chance.scramble.1": "박스 안이 혼전입니다. {player}가 밀어 넣으려 하지만 수비 숲을 뚫지 못합니다.",
		"comment.chance.scramble.2": "{club}, 두 번이나 공을 살립니다. {player}의 발끝 슛은 골문 앞에서 막힙니다.",
		"comment.chance.scramble.3": "흐른 공이 {player}에게 갑니다. 수비가 몸을 던지는 사이 급하게 때립니다.",
		"comment.save.scramble.1":   "{player}, 혼전 속에서 슛을 만들어내지만 골키퍼가 어떻게든 막아냅니다.",
		"comment.chance.counter.1":  "{club}, 역습으로 튀어나갑니다. 그러나 {player}의 마지막 터치가 길어집니다.",
		"comment.chance.counter.2":  "{player}, 앞에 넓은 공간과 지원을 두고도 빠른 슛을 옆으로 보냅니다.",
		"comment.chance.counter.3":  "{club}의 역습이 멋지게 열립니다. {player}가 마무리만 고르지 못합니다.",
		"comment.save.counter.1":    "{player}, 역습에서 단독 돌파. 골키퍼가 읽고 나와 막아냅니다.",
		"comment.card.yellow":       "경고 — {club}의 {player}, 옐로카드를 받습니다.",
		"comment.card.red":          "퇴장! {player}, {club}에서 퇴장당합니다.",
		"comment.card.secondyellow": "경고 누적 퇴장! {player} 물러납니다 — {club}, 10명으로 싸웁니다.",
		"comment.injury":            "{player} 쓰러졌습니다. {club} 치료가 필요합니다.",
		"comment.sub":               "{club} 교체 단행: {off} 대신 {on} 투입.",
		"comment.sub.fatigue":       "{off} 체력이 바닥났습니다 — {club}, {on}을(를) 대신 투입합니다.",
		"comment.sub.fresh":         "{club}의 새 활력: {off} 대신 {on} 투입.",
		"comment.sub.short":         "{player} 더 이상 뛸 수 없습니다 — {club}, 교체 카드 없이 수적 열세로 버팁니다.",
		"comment.quiet.1":           "양 팀이 서로를 살피는 조용한 시간입니다.",
		"comment.quiet.2":           "공이 미드필드를 오가지만 위협은 없습니다.",
		"comment.quiet.3":           "인내심 있는 빌드업, 그러나 결실은 없습니다.",
		"comment.quiet.4":           "잠시 템포가 내려갑니다. 양 벤치는 공보다 대형을 더 유심히 봅니다.",
		"comment.quiet.5":           "중원에서 소유권이 두 번 바뀌지만, 결정적인 패스는 나오지 않습니다.",
		"comment.quiet.6":           "조심스러운 패스가 이어지고 관중석에서는 낮은 웅성거림이 흐릅니다.",
		"comment.quiet.7":           "수비 라인이 단단히 버티며 경기를 센터서클 주변으로 밀어 넣습니다.",
		"comment.quiet.8":           "양쪽 풀백이 안전하게 공을 주고받는 사이 중원이 다시 간격을 맞춥니다.",
		"comment.quiet.9":           "좋은 각도가 잠깐 보였지만 압박이 길을 닫아 버립니다.",
		"comment.quiet.10":          "양 팀이 계속 찔러 보지만, 마지막 3분의 1은 여전히 빽빽합니다.",
		"comment.quiet.11":          "공이 좌우로 움직입니다. 아직은 위협보다 질문에 가깝습니다.",
		"comment.quiet.12":          "하프라인 부근의 무거운 터치 덕분에 수비가 한숨 돌립니다.",
		"comment.quiet.13":          "템포가 잠깐 올라가다 다시 신중한 중원 교환으로 내려옵니다.",
		"comment.quiet.14":          "대각 패스 하나가 그림을 바꾸는 듯했지만 커버 수비가 정리합니다.",
		"comment.quiet.15":          "관중은 패턴이 만들어지는 걸 느끼지만, 문을 여는 패스는 아직 나오지 않습니다.",
		"comment.halftime":          "전반 종료: {home_goals}–{away_goals}.",
		"comment.fulltime":          "경기 종료: {home} {home_goals}–{away_goals} {away}.",
		"comment.shootout":          "90분 무승부 — 승부차기 끝에 {winner} 진출 ({home} {home_pens}–{away_pens} {away}).",
		"comment.adj.push":          "{club}, 위험을 무릅쓰고 공격을 강화합니다.",

		// MCP UI 위젯 — 사람이 읽는 에이전트 행동 카드.
		"widget.badge.observed":           "관찰",
		"widget.badge.decided":            "결정",
		"widget.badge.read":               "읽음",
		"widget.app.mcp_app":              "MCP 앱",
		"widget.app.waiting":              "도구 결과를 기다리는 중...",
		"widget.app.problem":              "문제",
		"widget.app.tool_result":          "도구 결과",
		"widget.app.incomplete":           "호출이 완료되지 않았습니다.",
		"widget.focus.free":               "무료",
		"widget.focus.spent":              "−{spent} · {balance} 남음",
		"widget.version":                  "마인드셋 v{version}",
		"widget.pts":                      "{pts}점",
		"widget.headline.time":            "게임 시간과 진행 속도를 확인했습니다.",
		"widget.headline.settings":        "월드 설정과 게임 속도를 확인했습니다.",
		"widget.headline.generic":         "반환된 게임 정보를 확인했습니다.",
		"widget.headline.league":          "리그 순위를 확인했습니다.",
		"widget.headline.league.results":  "최근 경기 결과를 확인했습니다.",
		"widget.headline.league.fixtures": "다가오는 일정을 확인했습니다.",
		"widget.headline.league.managers": "디비전 감독진을 확인했습니다.",
		"widget.headline.disposition":     "감독 성향을 조정했습니다.",
		"widget.row.division":             "디비전",
		"widget.row.leaders":              "선두",
		"widget.row.clubs":                "클럽 수",
		"widget.row.results":              "최근 결과",
		"widget.row.fixtures":             "예정 경기",
		"widget.row.managers":             "감독",
		"widget.row.tempo":                "템포",
		"widget.row.speed":                "속도",
		"widget.row.next_match":           "다음 경기",
		"widget.row.world":                "월드",
		"widget.row.run_profile":          "진행 프로필",
		"widget.row.effective_speed":      "유효 속도",
		"widget.row.league_position":      "리그 순위",
		"widget.row.injuries":             "부상자",
		"widget.row.expiring_contracts":   "만료 예정 계약",
		"widget.section.next_fixture":     "다음 경기",
		"widget.section.last_results":     "최근 결과",
		"widget.section.headlines":        "헤드라인",
		"widget.section.table":            "상위 순위표",
		"widget.section.results":          "결과",
		"widget.section.fixtures":         "일정",
		"widget.disposition.drifting":     "현재 {current}, 이동 중",
		"widget.disposition.applied":      "즉시 적용",
		"widget.axis.D1":                  "리스크 성향",
		"widget.axis.D2":                  "유스 선호",
		"widget.axis.D3":                  "플레이 정체성",
		"widget.axis.D4":                  "재정 신중함",
		"widget.axis.D5":                  "충성심",
		"widget.axis.D6":                  "규율",
		"widget.axis.D7":                  "시간 지평",
		"widget.axis.D8":                  "미디어 태도",
		"widget.axis.D9":                  "전술 유연성",
		"widget.axis.D10":                 "개인 야망",

		// MCP UI 위젯 — 관측 조회 + 스카우트
		"widget.badge.scouted":       "스카우트",
		"widget.headline.situation":  "대시보드를 확인했습니다.",
		"widget.headline.news":       "최신 언론 기사를 읽었습니다.",
		"widget.headline.news.empty": "프레스룸을 확인했지만 새 기사는 없습니다.",
		"widget.row.phase":           "시기",
		"widget.row.headlines":       "헤드라인",
		"widget.headline.club":       "클럽 자료를 열었습니다.",
		"widget.headline.squad":      "스쿼드 시트를 확인했습니다.",
		"widget.headline.person":     "선수 자료를 열었습니다.",
		"widget.headline.manager":    "감독 자료를 열었습니다.",
		"widget.headline.match":      "경기를 확인했습니다.",
		"widget.headline.search":     "선수 시장을 검색했습니다.",
		"widget.headline.scout":      "스카우트 리포트를 의뢰했습니다.",
		"widget.row.club":            "클럽",
		"widget.row.items":           "새 소식",
		"widget.row.source":          "매체",
		"widget.row.category":        "섹션",
		"widget.row.players":         "선수 수",
		"widget.row.sample":          "예시",
		"widget.row.name":            "이름",
		"widget.row.position":        "포지션",
		"widget.row.age":             "나이",
		"widget.row.condition":       "컨디션",
		"widget.row.board":           "보드",
		"widget.row.fixture":         "경기",
		"widget.row.status":          "상태",
		"widget.row.score":           "스코어",
		"widget.row.competition":     "대회",
		"widget.row.found":           "검색 결과",
		"widget.row.top":             "최상위",
		"widget.row.due":             "리포트 예정",
		"widget.match.vs":            "{home} 대 {away}",
		"widget.match.FINISHED":      "경기 종료",
		"widget.match.LIVE":          "진행 중",
		"widget.match.SCHEDULED":     "예정",

		// MCP UI 위젯 — 셰이핑 쓰기 카드 (enum 값은 도메인 토큰으로 표시)
		"widget.headline.priorities":       "우선순위를 설정했습니다.",
		"widget.headline.directive_add":    "지시를 추가했습니다.",
		"widget.headline.directive_remove": "지시를 제거했습니다.",
		"widget.headline.tactical":         "전술을 조정했습니다.",
		"widget.row.count":                 "개수",
		"widget.row.top_priority":          "1순위",
		"widget.row.directive":             "지시",
		"widget.row.active":                "활성 지시",
		"widget.row.formation":             "포메이션",
		"widget.row.mentality":             "멘탈리티",
		"widget.row.pressing":              "압박",

		// World lifecycle (admin actions surface on the feed — A11)
		// Enum vocabularies — 위젯 카드의 enum 값 로컬라이즈.
		"enum.goal.AVOID_RELEGATION":    "강등 회피",
		"enum.goal.WIN_LEAGUE":          "리그 우승",
		"enum.goal.WIN_PROMOTION":       "승격 달성",
		"enum.goal.FINISH_TOP_N":        "상위권 마감",
		"enum.goal.CUP_RUN":             "컵 대회 선전",
		"enum.goal.DEVELOP_YOUTH":       "유스 육성",
		"enum.goal.FINANCIAL_HEALTH":    "재정 건전성",
		"enum.goal.BUILD_SQUAD_VALUE":   "스쿼드 가치 증대",
		"enum.goal.ESTABLISH_IDENTITY":  "팀 정체성 확립",
		"enum.goal.PROTECT_JOB":         "자리 보전",
		"enum.goal.FIND_JOB":            "일자리 찾기",
		"enum.verb.START":               "선발 기용",
		"enum.verb.BENCH":               "벤치 대기",
		"enum.verb.EXCLUDE":             "명단 제외",
		"enum.verb.ROTATE":              "로테이션",
		"enum.verb.GIVE_MINUTES":        "출전 시간 부여",
		"enum.verb.CAPTAIN":             "주장 임명",
		"enum.verb.SIGN":                "영입",
		"enum.verb.SELL":                "매각",
		"enum.verb.KEEP":                "잔류",
		"enum.verb.LOAN_OUT":            "임대 방출",
		"enum.verb.TARGET_PROFILE":      "프로필 타게팅",
		"enum.verb.RENEW":               "재계약",
		"enum.verb.RELEASE":             "방출",
		"enum.verb.WAGE_CAP":            "주급 상한",
		"enum.verb.DEVELOP":             "육성",
		"enum.verb.RETRAIN_POSITION":    "포지션 재훈련",
		"enum.verb.FORBID":              "금지",
		"enum.verb.PURSUE_JOB":          "구직 활동",
		"enum.verb.REJECT_JOB":          "제안 거절",
		"enum.verb.PUSH_BOARD":          "보드 압박",
		"enum.strength.LEAN":            "선호",
		"enum.strength.INSIST":          "강조",
		"enum.strength.ABSOLUTE":        "절대",
		"enum.mentality.VERY_DEFENSIVE": "극단적 수비",
		"enum.mentality.DEFENSIVE":      "수비적",
		"enum.mentality.BALANCED":       "균형",
		"enum.mentality.ATTACKING":      "공격적",
		"enum.mentality.VERY_ATTACKING": "극단적 공격",
		"enum.pressing.LOW":             "로우 프레스",
		"enum.pressing.MID":             "미드 프레스",
		"enum.pressing.HIGH":            "하이 프레스",
		"enum.tempo.SLOW":               "느린 템포",
		"enum.tempo.MIXED":              "혼합 템포",
		"enum.tempo.FAST":               "빠른 템포",
		"enum.width.NARROW":             "좁은 폭",
		"enum.width.MIXED":              "혼합 폭",
		"enum.width.WIDE":               "넓은 폭",
		"enum.directness.SHORT":         "짧은 패스",
		"enum.directness.MIXED":         "혼합 패스",
		"enum.directness.DIRECT":        "다이렉트 패스",

		"feed.world.started": "월드가 시작되었습니다.",
		"feed.world.paused":  "점검을 위해 월드가 일시정지되었습니다.",
		"feed.world.resumed": "월드가 재개되었습니다.",

		// API error surfaces (rendered per request locale)
		"error.bad_request":                             "잘못된 요청입니다.",
		"error.unknown_tier":                            "존재하지 않는 디비전입니다.",
		"error.unknown_club":                            "존재하지 않는 클럽입니다.",
		"error.not_found":                               "찾을 수 없습니다.",
		"error.internal":                                "내부 서버 오류입니다.",
		"error.admin_required":                          "어드민 토큰이 필요합니다.",
		"error.conflict":                                "현재 월드 상태와 충돌하는 요청입니다.",
		"error.runtime_settings.game_speed":             "게임 속도는 5, 15, 30, 60 중 하나여야 합니다.",
		"error.runtime_settings.idle_acceleration":      "일상 가속은 2부터 64 사이여야 합니다.",
		"error.runtime_settings.offseason_acceleration": "비시즌 가속은 2부터 240 사이여야 합니다.",
		"error.streaming_unsupported":                   "이 연결은 스트리밍을 지원하지 않습니다.",

		// MCP error surface (docs/11 §1.2)
		"err.auth_required":      "매니저 토큰이 필요합니다.",
		"err.invalid_token":      "알 수 없거나 교체된 매니저 토큰입니다.",
		"err.manager_retired":    "이미 은퇴한 감독입니다.",
		"err.focus.insufficient": "{required} FP가 필요하지만 잔액은 {balance} FP입니다.",
		"err.not_found":          "찾을 수 없습니다: {id}.",
		"err.invalid_target":     "타깃이 이 지시어와 맞지 않습니다.",
		"err.conflict":           "기존 지시({with})와 충돌합니다.",
		"err.cap_exceeded":       "허용 개수를 초과했습니다.",
		"err.unemployed_scope":   "클럽에 소속되어 있어야 합니다.",
		"err.validation":         "잘못된 요청: {detail}",

		// Reputation & mood descriptors (FR-22a hidden → observable)
		"desc.reputation.OBSCURE":     "무명",
		"desc.reputation.LOCAL":       "로컬",
		"desc.reputation.REGIONAL":    "지역",
		"desc.reputation.NATIONAL":    "전국구",
		"desc.reputation.CONTINENTAL": "대륙급",
		"desc.reputation.WORLDWIDE":   "월드클래스",
		"desc.mood.STEADY":            "안정적",

		// Player personality descriptors (docs/08 §5, FR-22a)
		"desc.player.CONSUMMATE_PROFESSIONAL": "완벽한 프로",
		"desc.player.DRIVEN":                  "야심가",
		"desc.player.TEAM_HEART":              "팀의 심장",
		"desc.player.IRON_NERVED":             "강심장",
		"desc.player.MERCENARY":               "용병 기질",
		"desc.player.VOLATILE":                "다혈질",
		"desc.player.GLASS_CANNON":            "유리몸 재능",
		"desc.player.HOMEBODY":                "향수병 기질",
		"desc.player.WALLFLOWER":              "존재감 희박",
		"desc.player.BALANCED":                "무난한 성격",

		// Board / club Descriptors
		"desc.confidence.HIGH":         "신뢰",
		"desc.confidence.MODERATE":     "관망",
		"desc.confidence.LOW":          "불안",
		"desc.injury.DAYS":             "가벼운 부상 — 며칠 결장",
		"desc.injury.WEEKS":            "부상 — 수 주 이탈",
		"desc.injury.MONTH":            "장기 부상 — 한 달 이상",
		"desc.form.IN_FORM":            "물오른 폼",
		"desc.form.STEADY":             "안정적",
		"desc.form.OUT_OF_FORM":        "폼 저하",
		"desc.form.UNKNOWN":            "검증 전",
		"desc.security.SECURE":         "안정적",
		"desc.security.STABLE":         "무난",
		"desc.security.UNDER_PRESSURE": "위태로움",
		"desc.facility.EXCELLENT":      "최상급",
		"desc.facility.GOOD":           "우수",
		"desc.facility.ADEQUATE":       "보통",
		"desc.facility.POOR":           "열악",

		// Manager style Descriptors (public reads on their football)
		"desc.style.IDEALIST":    "공격적 이상주의자",
		"desc.style.PRAGMATIST":  "결과 우선 실리주의자",
		"desc.style.FIREFIGHTER": "잔류 전문가",
		"desc.style.TRADER":      "시장형 감독",
		"desc.style.PROFESSOR":   "시스템 순수주의자",
		"desc.style.MOTIVATOR":   "선수단 관리형",
		"desc.style.TYRANT":      "철권 규율가",
		"desc.style.GAMBLER":     "고위험 승부사",

		// Scout evidence & news (docs/11 §4/§5)
		"evidence.professionalism.high":  "훈련에 전력을 다한다.",
		"evidence.professionalism.low":   "훈련과 준비에 태만한 편.",
		"evidence.ambition.high":         "정상에 오르려는 열망이 강하다.",
		"evidence.ambition.low":          "현실에 안주하며 승부욕이 부족하다.",
		"evidence.loyalty.high":          "구단에 대한 애착이 깊다.",
		"evidence.loyalty.low":           "조건만 맞으면 언제든 떠날 수 있다.",
		"evidence.temperament.high":      "도발에도 냉정을 유지한다.",
		"evidence.temperament.low":       "쉽게 흥분한다.",
		"evidence.pressure.high":         "압박이 심할수록 빛을 발한다.",
		"evidence.pressure.low":          "압박이 커지면 위축된다.",
		"evidence.adaptability.high":     "새 환경에 빠르게 적응한다.",
		"evidence.adaptability.low":      "새 환경에 적응이 더디다.",
		"evidence.sociability.high":      "라커룸에서 인기가 많다.",
		"evidence.sociability.low":       "동료들과 거리를 두는 편.",
		"evidence.influence.high":        "모두가 따르는 타고난 리더.",
		"evidence.influence.low":         "이끌기보다 따르는 데 만족한다.",
		"evidence.consistency.high":      "매주 꾸준한 기량을 보여준다.",
		"evidence.consistency.low":       "경기마다 기복이 심하다.",
		"evidence.big_match_nerve.high":  "큰 경기에서 더 강해진다.",
		"evidence.big_match_nerve.low":   "중요한 순간에 위축된다.",
		"evidence.injury_proneness.high": "잔부상이 잦다.",
		"evidence.injury_proneness.low":  "좀처럼 다치지 않는 강골.",
		"evidence.recovery.high":         "체력 회복이 빠르다.",
		"evidence.recovery.low":          "경기 사이 회복이 더디다.",
		"evidence.discipline.high":       "깔끔하고 규율 있는 플레이.",
		"evidence.discipline.low":        "거칠어 카드를 자주 받는다.",
		"evidence.versatility.high":      "여러 역할을 무리 없이 소화한다.",
		"evidence.versatility.low":       "한 역할에 특화된 전문가.",

		"news.scout.report":                  "{player} 스카우팅 보고서 도착 (깊이 {level}).",
		"news.decision.shift":                "{manager}({club}), 접근 방식을 다듬는 중.",
		"news.transfer.completed":            "{player}, 자유계약으로 {club} 입단.",
		"news.transfer.fee_completed":        "{club}, {from}에서 {player} 영입.",
		"news.board.warning":                 "{club} 구단주, 감독에게 비공개 경고.",
		"news.board.ultimatum":               "{club} 구단주, 감독에게 공개 최후통첩.",
		"news.board.reprieve":                "{club} 감독, 보드 신뢰 회복으로 한숨 돌리다.",
		"news.board.sacked":                  "{manager}, {club}에서 경질.",
		"news.board.caretaker":               "{manager}, {club} 감독대행 취임.",
		"news.board.appointed":               "{club}, {manager} 신임 감독 선임.",
		"news.board.caretaker_permanent":     "{club}, 감독대행 {manager} 정식 감독 선임.",
		"news.board.retired":                 "{manager}, 은퇴를 선언하다.",
		"news.youth.intake":                  "{club}, 유스 아카데미에서 유망주 {count}명 승격.",
		"news.youth.graduated":               "{club}, 아카데미 졸업생 {count}명 1군 합류.",
		"news.player.retired":                "{club}의 {player}, 현역 은퇴를 선언하다.",
		"news.player.retired_free":           "{player}, 선수 생활을 마감하다.",
		"news.contract.renewed":              "{club}, 선수 {count}명과 재계약 체결.",
		"news.contract.lapsed":               "{club}, 계약 만료로 선수 {count}명 방출.",
		"news.injury.days":                   "{club}의 {player}, 가벼운 부상으로 며칠 결장.",
		"news.injury.weeks":                  "{club}의 {player}, 부상으로 수 주간 이탈.",
		"news.injury.month":                  "{club} 비상 — {player}, 한 달 이상 장기 부상.",
		"news.article.source.transfer":       "이적 와이어",
		"news.article.source.match":          "매치 센터",
		"news.article.source.injury":         "메디컬 게시판",
		"news.article.source.board":          "클럽 데스크",
		"news.article.source.decision":       "훈련장 리포트",
		"news.article.source.career":         "리그 와이어",
		"news.article.source.youth":          "아카데미 데스크",
		"news.article.source.contract":       "계약 데스크",
		"news.article.source.scout":          "스카우팅 오피스",
		"news.article.source.media":          "카이저브루크 가제트",
		"news.article.deck.transfer":         "각 클럽이 스쿼드를 다시 짜는 가운데 이적 시장이 다시 움직였습니다.",
		"news.article.deck.match":            "종료 휘슬과 함께 리그 흐름에 또 하나의 장면이 더해졌습니다.",
		"news.article.deck.matchday.preview": "오늘의 경기 일정이 하나의 매치데이 브리핑으로 정리됐습니다.",
		"news.article.deck.matchday.results": "오늘의 점수가 모두 들어왔고, 순위표도 새 모양을 갖췄습니다.",
		"news.article.deck.injury":           "선발 계획에 영향을 줄 수 있는 몸 상태 이슈가 생겼습니다.",
		"news.article.deck.board":            "보드룸 압박이 새로운 전개로 이어졌습니다.",
		"news.article.deck.decision":         "감독의 최근 변화는 접근 방식이 달라지고 있음을 보여줍니다.",
		"news.article.deck.career":           "커리어 관련 결정이 감독 시장의 구도를 바꿨습니다.",
		"news.article.deck.youth":            "아카데미 파이프라인에서 새로운 소식이 나왔습니다.",
		"news.article.deck.contract":         "계약 업무가 스쿼드 구도에 변화를 만들었습니다.",
		"news.article.deck.scout":            "감독에게 비공개 스카우팅 파일이 전달됐습니다.",
		"news.article.deck.media":            "리그 주변의 최신 소식이 들어왔습니다.",
		"news.article.body.transfer":         "{headline}\n\n이번 움직임으로 이적 시장의 온도가 다시 올라갔습니다. 경쟁 클럽의 영입 담당자들은 후보 명단을 다시 확인할 가능성이 높고, 팬들은 이것이 단발성 보강인지 더 큰 개편의 시작인지 지켜볼 것입니다.\n\n당장 중요한 질문은 스쿼드 균형입니다. 누가 출전 시간을 얻고, 누가 밀려나며, 어느 감독이 다음 응답을 강요받는지가 시장의 다음 장면을 만들 것입니다.",
		"news.article.body.match":            "{headline}\n\n종료 휘슬은 점수만 확정하지 않았습니다. 순위표가 움직였고, 최근 흐름이 바뀌었으며, 양쪽 라커룸에는 다음 훈련 주간에 들고 갈 분명한 자료가 생겼습니다.\n\n승리한 쪽에는 계획이 작동한다는 또 하나의 근거가 됩니다. 패한 쪽은 결정적인 순간을 어디서 놓쳤는지부터 다시 봐야 합니다.",
		"news.article.body.matchday.preview": "{headline}\n\n경기 일정:\n{fixtures}\n\n첫 경기: {spotlight}. 같은 매치데이라도 각 감독에게 주어진 문제는 조금씩 다릅니다. 대형을 지키고, 먼저 흔들고, 어려운 오후가 긴 한 주의 해명으로 번지지 않게 막아야 합니다.\n\n다음 라운드업이 나올 때 순위표는 익숙할 수도 있고 완전히 다른 표정일 수도 있습니다. 계획을 말할 수 있는 팀과 피해를 설명해야 하는 팀은 첫 휘슬 뒤에 갈립니다.",
		"news.article.body.matchday.results": "{headline}\n\n결과:\n{results}\n\n순위표 흐름:\n{table}\n\n이야깃거리: {story}.\n\n점수는 혼자 서 있지 않습니다. 각 결과는 흐름, 신뢰, 다음 팀 토크를 조금씩 흔듭니다. 이긴 팀은 증거를 얻고, 진 팀은 영상을 다시 봐야 하며, 그 사이에 놓인 팀들은 오늘이 경고였는지 단순한 소음이었는지 판단해야 합니다.",
		"news.article.body.injury":           "{headline}\n\n메디컬 스태프는 상황을 계속 점검하겠지만, 선발 계획은 이미 조정이 필요합니다. 다음 명단은 감독이 선수층을 믿는지, 아니면 남은 전력을 보호하기 위해 계획 자체를 바꾸는지를 보여줄 것입니다.\n\n팬들은 결장이 짧기를 바라겠지만, 상대 팀은 그 빈자리를 곧바로 의식할 것입니다.",
		"news.article.body.board":            "{headline}\n\n시즌이 계속 움직이는 가운데 나온 소식이라, 앞으로의 모든 결과는 같은 압박계 위에서 해석될 것입니다. 보드의 신뢰는 문장 하나로만 움직이지 않지만, 팬들이 불안을 감지하면 흐름은 빠르게 바뀔 수 있습니다.\n\n이제 벤치에는 순위표를 움직이는 승점만큼이나 분위기를 잠재우는 경기력이 필요합니다.",
		"news.article.body.decision":         "{headline}\n\n변화는 먼저 선발에서, 다음에는 경기의 리듬에서 드러날 것입니다. 누가 출전하고, 누가 보호받으며, 감독이 어디에 리스크를 쓰는지가 관찰 대상입니다.\n\n훈련장 주변의 메시지는 분명합니다. 앞으로 몇 경기가 이것이 확신인지 실험인지 가르게 됩니다.",
		"news.article.body.career":           "{headline}\n\n감독 관련 움직임은 사무실 문 하나만 바꾸지 않습니다. 선수들은 메시지를 읽고, 보드는 비교하고, 무직 감독들은 조용히 다음 기회를 다시 계산합니다.\n\n팬들에게는 더 단순합니다. 새로운 목소리, 달라진 터치라인, 그리고 다음 휘슬 전까지 커진 기대입니다.",
		"news.article.body.youth":            "{headline}\n\n아카데미 스태프에게 필요한 것은 재능만큼이나 인내입니다. 이 이름들 중 일부는 1군에 의미를 갖기까지 몇 시즌이 걸릴 수 있지만, 좋은 클럽은 관중이 알기 전부터 그런 이야기를 준비합니다.\n\n지금 코치진이 보는 것은 태도, 신체 성장, 그리고 얼마나 빨리 성인 무대의 기준을 흡수하는지입니다.",
		"news.article.body.contract":         "{headline}\n\n계약 업무는 경기 당일 큰 소리를 내지 않지만, 매주 라커룸의 모양을 바꿉니다. 누가 프로젝트에 묶이는지에 따라 주급 여유, 선수층, 여름 시장의 유연성이 모두 달라집니다.\n\n다음 시장이 열리면 이것이 단순 정리였는지, 더 큰 움직임을 위한 준비였는지가 드러날 것입니다.",
		"news.article.body.scout":            "{headline}\n\n이 파일은 영입과 선발 회의에 새로운 근거를 더합니다. 좋은 스카우팅은 결정을 대신하지 않습니다. 다만 리스크를 좁히고, 어떤 질문을 더 지켜봐야 하는지 알려줍니다.\n\n다음 선택은 재확인, 빠른 실행, 혹은 더 넓은 탐색 속에 보고서를 넣는 일입니다.",
		"news.article.body.media":            "{headline}\n\n리그 주변에서 이런 이야기는 오래 혼자 남지 않습니다. 한 캠프의 작은 변화가 보드, 팬, 감독들의 비교 속에서 다른 캠프의 압박으로 번질 수 있습니다.\n\n추가 정보도 중요하겠지만, 이미 이번 주 대화 속에 들어온 신호입니다.",

		// Shared terms
		"term.free_agent":                   "무소속",
		"term.window.summer":                "여름",
		"term.window.winter":                "겨울",
		"term.competition.LEAGUE":           "리그",
		"term.competition.CUP":              "컵",
		"term.matchday.fixture_line":        "{round}라운드: {home} 대 {away}",
		"term.matchday.fixture_spotlight":   "{home} 대 {away}",
		"term.matchday.result_line":         "{home} {home_goals}-{away_goals} {away}",
		"term.matchday.result_line.winner":  "{home} {home_goals}-{away_goals} {away}; {winner} 진출",
		"term.matchday.table_leader":        "{division}부: {club}, 승점 {points}로 선두",
		"term.matchday.table_cup":           "컵 일정은 리그 순위표 대신 대진표를 다시 움직였습니다",
		"term.matchday.story_margin":        "최다 점수 차: {best_home} {home_goals}-{away_goals} {best_away}",
		"term.matchday.story_draws":         "무승부 {draws}경기",
		"term.matchday.story_all_winners":   "무승부가 없어 순위표의 움직임도 더 선명했습니다",
		"term.matchday.story_unavailable":   "이번 라운드업의 이야기 데이터가 부족했습니다",
		"term.chance_type.CROSS_HEADER":     "크로스 헤더",
		"term.chance_type.CUTBACK":          "컷백",
		"term.chance_type.THROUGH_BALL":     "스루패스",
		"term.chance_type.LONG_SHOT":        "중거리 슛",
		"term.chance_type.SET_PIECE_HEADER": "세트피스 헤더",
		"term.chance_type.SCRAMBLE":         "문전 혼전",
		"term.chance_type.COUNTER":          "역습",
		"term.quality.HIGH":                 "높음",
		"term.quality.MEDIUM":               "보통",
		"term.quality.LOW":                  "낮음",
		"term.tempo.MATCH":                  "매치",
		"term.tempo.IDLE":                   "일상",
		"term.tempo.OFFSEASON":              "비시즌",
		"term.tempo.PAUSED":                 "일시정지",
		"term.state.ready":                  "대기",
		"term.state.running":                "진행 중",
		"term.state.paused":                 "일시정지",

		// Positional familiarity descriptors (docs/08 §2)
		"desc.familiarity.NATURAL":      "최적",
		"desc.familiarity.ACCOMPLISHED": "능숙",
		"desc.familiarity.COMPETENT":    "준수",
		"desc.familiarity.AWKWARD":      "어색",
		"desc.weak_foot.STRONG":         "강함",
		"desc.weak_foot.USEFUL":         "쓸 만함",
		"desc.weak_foot.LIMITED":        "제한적",
		"desc.weak_foot.ONE_FOOTED":     "한발 의존",

		// Visible attribute display names (docs/08 §2)
		"attr.FINISHING":       "골 결정력",
		"attr.LONG_SHOTS":      "중거리 슛",
		"attr.FIRST_TOUCH":     "퍼스트 터치",
		"attr.PASSING":         "패스",
		"attr.CROSSING":        "크로스",
		"attr.DRIBBLING":       "드리블",
		"attr.TECHNIQUE":       "기술",
		"attr.HEADING":         "헤딩",
		"attr.TACKLING":        "태클",
		"attr.MARKING":         "마킹",
		"attr.SET_PIECES":      "세트피스",
		"attr.AGGRESSION":      "적극성",
		"attr.VISION":          "시야",
		"attr.DECISIONS":       "판단력",
		"attr.COMPOSURE":       "침착성",
		"attr.CONCENTRATION":   "집중력",
		"attr.POSITIONING":     "위치 선정",
		"attr.OFF_BALL":        "오프 더 볼",
		"attr.ANTICIPATION":    "예측력",
		"attr.WORK_RATE":       "활동량",
		"attr.BRAVERY":         "용감성",
		"attr.TEAMWORK":        "팀워크",
		"attr.LEADERSHIP":      "리더십",
		"attr.DETERMINATION":   "투지",
		"attr.FLAIR":           "창의성",
		"attr.ACCELERATION":    "가속력",
		"attr.PACE":            "스피드",
		"attr.AGILITY":         "민첩성",
		"attr.BALANCE":         "균형감",
		"attr.STRENGTH":        "힘",
		"attr.STAMINA":         "지구력",
		"attr.NATURAL_FITNESS": "타고난 체력",
		"attr.JUMPING_REACH":   "점프 리치",
		"attr.REFLEXES":        "반사신경",
		"attr.ONE_ON_ONES":     "1대1",
		"attr.HANDLING":        "핸들링",
		"attr.AERIAL_REACH":    "공중 리치",
		"attr.COMMAND_OF_AREA": "박스 장악",
		"attr.COMMUNICATION":   "소통",
		"attr.DISTRIBUTION":    "볼 배급",
		"attr.SWEEPING":        "스위핑",
		"attr.ECCENTRICITY":    "기행",
		"attr.PUNCHING":        "펀칭",
		"attr.DEFENDING":       "수비",
		"attr.AERIAL":          "공중볼",
		"attr.SHOT_STOPPING":   "선방",
		"attr.AERIAL_COMMAND":  "공중 장악",

		// Console UI chrome
		"ui.app.title":                                 "Agentic FC",
		"ui.tab.media":                                 "매체",
		"ui.tab.table":                                 "순위표",
		"ui.tab.clubs":                                 "클럽",
		"ui.tab.fixtures":                              "일정/결과",
		"ui.tab.admin_settings":                        "설정",
		"ui.col.pos":                                   "순위",
		"ui.col.club":                                  "클럽",
		"ui.col.div":                                   "부",
		"ui.col.security":                              "직위",
		"ui.col.source":                                "매체",
		"ui.col.article":                               "기사",
		"ui.col.name":                                  "이름",
		"ui.col.age":                                   "나이",
		"ui.col.position":                              "포지션",
		"ui.col.attributes":                            "능력치",
		"ui.col.contract":                              "계약",
		"ui.col.played":                                "경기",
		"ui.col.won":                                   "승",
		"ui.col.drawn":                                 "무",
		"ui.col.lost":                                  "패",
		"ui.col.gf":                                    "득점",
		"ui.col.ga":                                    "실점",
		"ui.col.pts":                                   "승점",
		"ui.col.round":                                 "R",
		"ui.col.kickoff":                               "킥오프",
		"ui.col.fixture":                               "대진",
		"ui.col.status":                                "상태",
		"ui.table.live":                                "실시간 순위",
		"ui.fixtures.empty":                            "표시할 일정이나 결과가 없습니다.",
		"ui.fixture.live":                              "진행중",
		"ui.fixture.scheduled":                         "예정",
		"ui.fixture.result":                            "결과",
		"ui.fixture.replay":                            "리플레이",
		"ui.fixture.archived":                          "아카이브",
		"ui.fixture.scheduled_notice":                  "아직 킥오프하지 않은 경기입니다.",
		"ui.match.none":                                "진행 중인 경기가 없습니다 — 구장은 고요합니다.",
		"ui.match.loading":                             "경기 상세를 불러오는 중입니다...",
		"ui.match.legend":                              "G 골 · o 기회 · x 카드 · + 부상 · s 교체 · ! 승부차기",
		"ui.match.scoreboard":                          "전광판",
		"ui.match.goalflash":                           "골",
		"ui.match.live":                                "라이브 경기",
		"ui.match.ended":                               "경기가 종료되었습니다 — 리플레이가 결과에 표시됩니다.",
		"ui.match.waiting_result":                      "경기 종료 기록을 반영하는 중입니다. 결과 기록을 기다립니다...",
		"ui.match.modal.close":                         "Esc 닫기 · ←/→ 다른 경기",
		"ui.match.modal.replay_help":                   "Esc 닫기 · PgUp/PgDn 또는 ←/→ 되감기/앞감기",
		"ui.match.stats":                               "경기 스탯",
		"ui.match.ratings":                             "평점",
		"ui.match.latest":                              "다른 경기장",
		"ui.match.momentum":                            "흐름",
		"ui.match.away":                                "원정",
		"ui.match.winner":                              "승자",
		"ui.match.scorers":                             "득점",
		"ui.match.cards":                               "카드",
		"ui.match.subs":                                "교체",
		"ui.match.replay":                              "리플레이 로그",
		"ui.match.replay.more":                         "PageDown으로 리플레이를 더 봅니다.",
		"ui.match.replay.archived":                     "아카이브 결과입니다: 해설 리플레이는 보존되지 않았습니다.",
		"ui.match.stat.shots":                          "슈팅",
		"ui.match.stat.cards":                          "카드",
		"ui.match.stat.subs":                           "교체",
		"ui.match.stat.chance_mix":                     "찬스 유형",
		"ui.match.stat.quality":                        "슛 품질",
		"ui.match.stat.aerial":                         "공중볼",
		"ui.match.stat.press":                          "압박",
		"ui.match.stat.setpieces":                      "세트피스",
		"ui.header.division":                           "{tier}부 리그",
		"ui.help.keys":                                 "1 매체 · 2 순위표 · 3 클럽 · 4 결과 · Enter/Space/클릭 라이브·리플레이 열기 · ←/→ 라이브 경기/리플레이 · Esc 닫기 · PgUp/PgDn 리플레이 · q 종료",
		"ui.help.keys_admin":                           "1 매체 · 2 순위표 · 3 클럽 · 4 결과 · 5 설정 · +/- 또는 [/] 조정 · ↑/↓ 선택 · q 종료",
		"ui.admin.token_required":                      "관리자 토큰이 필요합니다.",
		"ui.admin.settings.loading":                    "설정을 불러오는 중입니다...",
		"ui.admin.settings.title":                      "런타임 설정",
		"ui.admin.settings.help":                       "↑/↓로 페이싱 설정을 선택하고 +/- 또는 [/ ]로 즉시 조정합니다.",
		"ui.admin.settings.setting":                    "설정",
		"ui.admin.settings.value":                      "값",
		"ui.admin.settings.allowed":                    "허용 범위",
		"ui.admin.settings.game_speed":                 "게임 속도",
		"ui.admin.settings.idle_acceleration":          "일상 가속",
		"ui.admin.settings.offseason_acceleration":     "비시즌 가속",
		"ui.admin.settings.determinism":                "결정론",
		"ui.admin.settings.determinism_body":           "런타임 페이싱은 실제 시간 지연만 바꾸며, 게임 시간 순서와 결과는 바뀌지 않습니다.",
		"ui.admin.settings.rebuild_required":           "새 월드가 필요한 설정",
		"ui.admin.settings.rebuild.seed":               "시드",
		"ui.admin.settings.rebuild.divisions":          "디비전 수",
		"ui.admin.settings.rebuild.clubs_per_division": "디비전별 클럽 수",
		"ui.admin.settings.rebuild.quality":            "월드 품질",
		"ui.admin.settings.rebuild.economy":            "경제 설정",
		"ui.admin.settings.rebuild.culture_mix":        "이름 문화권 구성",
		"ui.admin.settings.saved":                      "런타임 설정이 변경되었습니다.",
		"ui.terminal.too_small":                        "터미널이 너무 작습니다 — 최소 {min_cols}×{min_rows} 필요 (현재 {cols}×{rows}).",
		"ui.mode.viewer":                               "뷰어",
		"ui.mode.admin":                                "어드민",
		"ui.feed.waiting":                              "월드 소식을 기다리는 중…",
		"ui.notice.news":                               "새 기사: {title}",
		"ui.notice.match":                              "라이브 경기 {count}개가 시작됐습니다.",
		"ui.media.empty":                               "아직 보도된 기사가 없습니다 — 첫 소식을 기다리는 중입니다.",
		"ui.media.recent":                              "최근 보도",
		"ui.clubs.empty":                               "클럽 정보를 가져오지 못했습니다.",
		"ui.club.caretaker":                            "감독대행 체제",
		"ui.club.manager":                              "감독",
		"ui.club.predicted":                            "예상",
		"ui.club.objective":                            "목표",
		"ui.club.confidence":                           "보드",
		"ui.club.security":                             "직위",
		"ui.club.fan_mood":                             "팬",
		"ui.club.balance":                              "잔고",
		"ui.club.wage_bill":                            "주급",
		"ui.club.transfer_budget":                      "이적예산",
		"ui.club.squad":                                "선수단",
		"ui.player.empty":                              "선택된 선수가 없습니다.",
		"ui.player.dossier":                            "선수 파일",
		"ui.player.group":                              "유닛",
		"ui.player.body":                               "신체",
		"ui.player.foot":                               "발",
		"ui.player.familiarity":                        "적응도",
		"ui.player.profile":                            "능력치 프로필",
		"ui.player.youth":                              "아카데미 선수",
		"ui.error.prefix":                              "문제:",
		"ui.clock":                                     "시즌 {season} · {month} {day}일 {hh}:{mm}",
		"ui.month.1":                                   "1월",
		"ui.month.2":                                   "2월",
		"ui.month.3":                                   "3월",
		"ui.month.4":                                   "4월",
		"ui.month.5":                                   "5월",
		"ui.month.6":                                   "6월",
		"ui.month.7":                                   "7월",
		"ui.month.8":                                   "8월",
		"ui.month.9":                                   "9월",
		"ui.month.10":                                  "10월",
		"ui.month.11":                                  "11월",
		"ui.month.12":                                  "12월",
	},
}
